name: Release
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  newrelic:
    runs-on: ubuntu-latest
    steps:
      - name: Create New Relic deployment marker
        uses: newrelic/deployment-marker-action@v1
        with:
          accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          applicationId: ${{ secrets.NEW_RELIC_APPLICATION_ID }}
          revision: "${{ github.ref }}-${{ github.sha }}"
          changelog: "See https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md for details"
          description: "Automated Deployment via GitHub Actions"
          user: "${{ github.actor }}"
